
ps_ip: 10.30.72.19

worker_ips: 
    - agent1:[1]
    - agent2:[1]
    # - agent3:[1]
    # - agent4:[1]
    # - agent5:[1]
    # - agent6:[1]
    # - agent7:[1]
    # - agent8:[1]
    # - agent9:[1]
    # - agent10:[1]
    # - agent11:[1]
    # - agent12:[1]
    # - agent13:[1]
    # - agent14:[1]
    # - agent15:[1]
    # - agent16:[1]
    # - agent17:[1]
    # - agent18:[1]
    # - agent19:[1]
    # - agent20:[1]
    # - agent21:[1]
    # - agent22:[1]
    # - agent23:[1]
    # - agent24:[1]
    # - agent25:[1]
    # - agent26:[1]
    # - agent27:[1]
    # - agent28:[1]
    # - agent29:[1]
    # - agent30:[1]
    # - agent31:[1]
    # - agent32:[1]
    # - agent33:[1]
    # - agent34:[1]
    # - agent35:[1]
    # - agent36:[1]
    # - agent37:[1]
    # - agent38:[1]
    # - agent39:[1]
    # - agent40:[1]
    # - agent41:[1]
    # - agent42:[1]
    # - agent43:[1]
    # - agent44:[1]
    # - agent45:[1]
    # - agent46:[1]
    # - agent47:[1]
    # - agent48:[1]
    # - agent49:[1]
    # - agent50:[1]
    # - agent51:[1]
    # - agent52:[1]
    # - agent53:[1]
    # - agent54:[1]
    # - agent55:[1]
    # - agent56:[1]
    # - agent57:[1]
    # - agent58:[1]
    # - agent59:[1]
    # - agent60:[1]
    # - agent61:[1]
    # - agent62:[1]
    # - agent63:[1]
    # - agent64:[1]
    # - agent65:[1]
    # - agent66:[1]
    # - agent67:[1]
    # - agent68:[1]
    # - agent69:[1]
    # - agent70:[1]
    # - agent71:[1]
    # - agent72:[1]
    # - agent73:[1]
    # - agent74:[1]
    # - agent75:[1]
    # - agent76:[1]
    # - agent77:[1]
    # - agent78:[1]
    # - agent79:[1]
    # - agent80:[1]
    # - agent81:[1]
    # - agent82:[1]
    # - agent83:[1]
    # - agent84:[1]
    # - agent85:[1]
    # - agent86:[1]
    # - agent87:[1]
    # - agent88:[1]
    # - agent89:[1]
    # - agent90:[1]
    # - agent91:[1]
    # - agent92:[1]
    # - agent93:[1]
    # - agent94:[1]
    # - agent95:[1]
    # - agent96:[1]
    # - agent97:[1]
    # - agent98:[1]
    # - agent99:[1]
    # - agent100:[1]

exp_path: $HOME/FedScale/core

executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

setup_commands:
    - source $HOME/anaconda3/bin/activate fedscale
    - export NCCL_SOCKET_IFNAME='eth0' 

job_conf: 
    - job_name: femnist
    - log_path: $HOME/FedScale/core/evals
    - logging_level: DEBUG
    - total_worker: 4 # This is the number of clients (for training)
    - data_set: femnist
    - data_dir: $HOME/FedScale/dataset/data/femnist
    - data_map_file: $HOME/FedScale/dataset/data/femnist/client_data_mapping/train.csv
    # - gradient_policy: yogi
    - eval_interval: 2
    - epochs: 3
    - filter_less: 21
    - num_loaders: 1
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    - local_steps: 20
    - learning_rate: 0.05
    - batch_size: 20
    - test_bsz: 20
    - malicious_factor: 4
    - logging_step: 10
