
ps_ip: 10.30.72.19

worker_ips: 
    # - agent1:[1] #small
    # - agent2:[1] #small
    - agent3:[1]
    - agent4:[1]
    - agent5:[1]
    - agent6:[1]
    - agent7:[1]
    - agent8:[1]
    - agent9:[1]
    - agent10:[1]
    - agent11:[1]
    - agent12:[1]
    - agent13:[1]
    - agent14:[1]
    - agent15:[1]
    - agent16:[1]
    - agent17:[1]
    - agent18:[1]
    - agent19:[1]
    - agent20:[1]
    - agent21:[1]
    - agent22:[1]
    - agent23:[1]
    - agent24:[1]
    - agent25:[1]
    - agent26:[1]
    - agent27:[1]
    - agent28:[1]
    - agent29:[1]
    - agent30:[1]
    - agent31:[1]
    - agent32:[1]
    - agent33:[1]
    - agent34:[1]
    - agent35:[1]
    - agent36:[1]
    - agent37:[1]
    - agent38:[1]
    - agent39:[1]
    - agent40:[1]

exp_path: $HOME/FedScale/core

executor_entry: executor.py

aggregator_entry: aggregator.py

auth:
    ssh_user: ""
    ssh_private_key: ~/.ssh/id_rsa

setup_commands:
    - source $HOME/anaconda3/bin/activate fedscale
    - export NCCL_SOCKET_IFNAME='eth0' 

job_conf: 
    - job_name: femnist
    - log_path: $HOME/FedScale/core/evals
    - total_worker: 38
    - data_set: femnist
    - data_dir: $HOME/FedScale/dataset/data/femnist
    - data_map_file: $HOME/FedScale/dataset/data/femnist/client_data_mapping/train.csv
    - gradient_policy: yogi
    - eval_interval: 30
    - epochs: 2
    - filter_less: 21
    - num_loaders: 1
    - yogi_eta: 3e-3 
    - yogi_tau: 1e-8
    - local_steps: 20
    - learning_rate: 0.05
    - batch_size: 20
    - test_bsz: 20
    - malicious_factor: 4
    - logging_step: 10
